travis:
  secure:
    BINSTAR_TOKEN: v0mvI/xxHfeEBJmgcfIHLLSpQzD9ZU1Fb5X6s/9po8fszmneoHBFoOPAruya1F/EdERT9Oij0yQsZHu4BxO/0Zk29S7+Zw7hPF/nWJIt/VGuACT8AWGuDQVGqpodnD23tC/oCQNHDxFogLCn7DGp/nm7oQHUDGRDh6X2lN1wC9qmLfcOCbs04TBjaY76yATsV6TMB+Quw4eOYeRNAMLvlwp4+t46eGTwun1V9RviwZd744EpBRXm4aQVb7l+l+7eAFVFvz8VzDnCpsi+uIQ2/BbaPyQjhp4dt2HGp1MLDtfNAGIBKmFNcQ+dloFKdpKFr5C7CLyBNO0bn2T+QlkoFknYODUhBqWBK14U1Ti42x/qjp919xzqbd0BaRU8A7FISApkW0m7YtjmMIkETfiAgFM2Za+tEWEIRrRwg5csBp5OZnioGz3FH96fro2A3SqGrO2NESV1ndNf0KtW1IjcLU2oN/d/NrmeDwiFtiQPHH4AYiD6LK8G7AWnXB8O59YGfNzoO9UnW6nnCFNBkROgRRxUXb83eqAyyTFkkwfKxoZU9TT+IwxMRLu3SKzpF+aBGaisToxxSORzBhYuH83L3Iz54oq6JieI/weIOxXQB+D5UchhcO5x40jX2lW33W785gLjCQDQaNe2pvlV9kRyM6f63paN6rUVG741Jol/hkc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
